### PR TITLE
fix footer position with window.innerHeight

### PR DESCRIPTION
**Pull request by dirk122119**
陳冠守
http://54.64.173.185:3000/
http://54.64.173.185:3000/attraction/2

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Slider image in mobile version should keep no margin space with navigator bar.
2. Layout details: padding, color, size
54 64 173 185_3000_attraction_2

**Comment by dirk122119** [comment]
fix

**Review by cwpeng — CHANGES_REQUESTED** [review]
Padding of date input.

**Comment by dirk122119** [comment]
git pull and redeploy it on ec2 again

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
