### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by dirk122119**
陳冠守,Get on the car#1781
http://54.64.173.185:3000/api/attractions?page=1
http://54.64.173.185:3000/api/attractions?page=0&keyword=公共藝術
http://54.64.173.185:3000/api/attractions?page=0&keyword=北
http://54.64.173.185:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Result is OK. But It's much better to use `LIMIT` in SQL to do pagination than get ALL DATA and do it in your own code.

Fix this issue and re-request review.

**Comment by dirk122119** [comment]
I have used `LIMIT` in SQL to do pagination, please check it.

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
